### ISSUE TITLE
Dropping `php-7.0` version support

### ISSUE THREAD

**Issue by peter279k** [laravie/geotools#1]
As title, it seems that the `php-7.0` version will be unsupported at recent time.

IMHO, we should consider dropping `php-7.0` version and keep this package requiring stable PHP version (It may be a `php-7.1+` versions) at least.

**Comment by crynobone** [comment]
https://github.com/laravie/geotools/compare/v1.0.2..master

`dev-master` already updated to 7.1 and above, but I still don't see anything significant at the moment to merit 7.0 deprecation.
